import type { Post, User, TrendingTopic, TrendingUser } from "./store"

export const dummyUser: User = {
  id: "1",
  name: "John Doe",
  username: "johndoe",
  avatar: "/diverse-user-avatars.png",
  bio: "Always waiting for something interesting",
  followers: 1234,
  following: 567,
  posts: 89,
}

export const dummyPosts: Post[] = [
  {
    id: "1",
    author: {
      id: "2",
      name: "Alex",
      username: "alex",
      avatar: "/alex-avatar.png",
    },
    content: "Waiting for a train",
    timeLeft: "23 h left",
    likes: 1,
    comments: 0,
    shares: 0,
    isLiked: false,
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    author: {
      id: "3",
      name: "Anonymous",
      username: "anonymous",
      avatar: "/anonymous-avatar.png",
      isAnonymous: true,
    },
    content: "Getting dinner ready",
    timeLeft: "23 h left",
    likes: 1,
    comments: 0,
    shares: 0,
    isLiked: false,
    createdAt: "2024-01-15T09:45:00Z",
  },
  {
    id: "3",
    author: {
      id: "4",
      name: "Madida",
      username: "madida",
      avatar: "/stylized-female-avatar.png",
    },
    content: "Starting a new job",
    timeLeft: "23 h left",
    likes: 1,
    comments: 0,
    shares: 0,
    isLiked: false,
    createdAt: "2024-01-15T09:15:00Z",
  },
  {
    id: "4",
    author: {
      id: "5",
      name: "Provide",
      username: "provide",
      avatar: "/generic-avatar.png",
    },
    content: "Terminal update to finish downloading",
    timeLeft: "23 h left",
    likes: 1,
    comments: 0,
    shares: 0,
    isLiked: false,
    createdAt: "2024-01-15T08:30:00Z",
  },
]

export const dummyTrendingTopics: TrendingTopic[] = [
  {
    id: "1",
    name: "Weekend plans",
    count: 1247,
    category: "topic",
    growth: 15.3,
    isRising: true,
  },
  {
    id: "2",
    name: "#ExamResults",
    count: 892,
    category: "hashtag",
    growth: 8.7,
  },
  {
    id: "3",
    name: "Movie night",
    count: 634,
    category: "topic",
    growth: -2.1,
  },
  {
    id: "4",
    name: "#BookRelease",
    count: 567,
    category: "hashtag",
    growth: 23.4,
    isRising: true,
  },
  {
    id: "5",
    name: "Game night",
    count: 445,
    category: "topic",
    growth: 5.8,
  },
  {
    id: "6",
    name: "Concert tickets",
    count: 389,
    category: "event",
    growth: 12.9,
  },
  {
    id: "7",
    name: "#JobInterview",
    count: 298,
    category: "hashtag",
    growth: 18.2,
    isRising: true,
  },
  {
    id: "8",
    name: "Vacation approval",
    count: 234,
    category: "topic",
    growth: 7.4,
  },
]

export const dummyTrendingUsers: TrendingUser[] = [
  {
    id: "trending1",
    name: "Sarah Chen",
    username: "sarahc",
    avatar: "/stylized-female-avatar.png",
    followers: 12400,
    growth: 25.3,
    isVerified: true,
  },
  {
    id: "trending2",
    name: "Mike Johnson",
    username: "mikej",
    avatar: "/alex-avatar.png",
    followers: 8900,
    growth: 18.7,
  },
  {
    id: "trending3",
    name: "Emma Wilson",
    username: "emmaw",
    avatar: "/diverse-user-avatars.png",
    followers: 6700,
    growth: 15.2,
    isVerified: true,
  },
  {
    id: "trending4",
    name: "Alex Rivera",
    username: "alexr",
    avatar: "/generic-avatar.png",
    followers: 5400,
    growth: 12.8,
  },
]
